version: '3'
services:
  web:
    image: odoo:17.0
    ports:
      - "8069:8069"
      - "8072:8072"  # Live chat port
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo:rw
      - ./custom:/mnt/addons/custom:rw
      - ./enterprise:/mnt/addons/enterprise:rw
      - ./data:/var/lib/odoo/data:rw
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: -- --dev=reload
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data: