services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - odoo-network

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./logs:/var/log/odoo
      - .:/mnt/extra-addons
    networks:
      - odoo-network
    command: >
      odoo 
      --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
      --db_host=db
      --db_port=5432
      --db_user=odoo
      --db_password=odoo
      --logfile=/var/log/odoo/odoo.log
      --log-level=info
      --without-demo=all

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo-network:
    driver: bridge
