<<<<<<< HEAD
=======
version: '3.1'
>>>>>>> 28b8df81 (INIT)
services:
  db:
    image: postgres:16
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  web:
    image: odoo:17.0
    depends_on:
      - db
    volumes:
      - ./data/odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom:/mnt/addons/custom
      - ./enterprise:/mnt/addons/enterprise
    ports:
      - "8069:8069"
