# Odoo Framework Type Stubs for VS Code
# This file helps VS Code understand Odoo imports and reduces red squiggly lines

from typing import Any, Dict, List, Optional, Union

# Odoo core imports
class fields:
    @staticmethod
    def Char(*args, **kwargs) -> Any: ...
    @staticmethod
    def Text(*args, **kwargs) -> Any: ...
    @staticmethod
    def Integer(*args, **kwargs) -> Any: ...
    @staticmethod
    def Float(*args, **kwargs) -> Any: ...
    @staticmethod
    def Boolean(*args, **kwargs) -> Any: ...
    @staticmethod
    def Date(*args, **kwargs) -> Any: ...
    @staticmethod
    def Datetime(*args, **kwargs) -> Any: ...
    @staticmethod
    def Binary(*args, **kwargs) -> Any: ...
    @staticmethod
    def Selection(*args, **kwargs) -> Any: ...
    @staticmethod
    def Many2one(*args, **kwargs) -> Any: ...
    @staticmethod
    def One2many(*args, **kwargs) -> Any: ...
    @staticmethod
    def Many2many(*args, **kwargs) -> Any: ...

class models:
    class Model:
        env: Any
        _name: str
        _description: str
        _inherit: Union[str, List[str]]
        _order: str
        id: int
        create_uid: Any
        write_uid: Any
        create_date: Any
        write_date: Any
        
        def create(self, vals: Dict) -> Any: ...
        def write(self, vals: Dict) -> Any: ...
        def unlink(self) -> Any: ...
        def search(self, domain: List, **kwargs) -> Any: ...
        def browse(self, ids: List[int]) -> Any: ...
        def ensure_one(self) -> None: ...
        def message_post(self, **kwargs) -> Any: ...

class api:
    @staticmethod
    def depends(*args) -> Any: ...
    @staticmethod
    def model(func) -> Any: ...
    @staticmethod
    def constrains(*args) -> Any: ...
    @staticmethod
    def onchange(*args) -> Any: ...

def _(text: str) -> str: ...

# Odoo exceptions
class ValidationError(Exception): ...
class UserError(Exception): ...
class AccessError(Exception): ...
