version: '3.8'

services:
  jotform-webhook:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - jotform-network

networks:
  jotform-network:
    driver: bridge
